server:
  port: 81
  tomcat:
    max-connections: 100000
    max-threads: 20000

    resource:
      allow-caching: true
  servlet:
    session:
      timeout: 480m

spring:
  profiles:
    active: test
  fileUploadPath:
    path: /root/OJ/oj_file/
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: paraf214%^&*
    jedis:
      pool:
        max-active: 1000
        max-wait: -1
        max-idle: 5
        min-idle: 0
    timeout: 10000
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/teaching?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&useAffectedRows=true
    username: root
    password: paraf214%^&*
    driver-class-name: com.mysql.jdbc.Driver
#    hikari:
#      maximum-pool-size: 500
#      connection-timeout: 120000
#      max-lifetime: 120000
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
  resources:
    static-locations: classpath:/static,classpath:/templates,file:${spring.fileUploadPath.path}
logging:
  path: /root/OJ/oj_front_log
debug: false